language: elixir

env:
  - MIX_ENV=test

elixir:
  - 1.5

otp_release:
  - 20.0

sudo: true

services:
  - docker
  - postgresql

addons:
  chrome: stable
  postgresql: "9.6"

before_script:
  - mix compile
  - mix ecto.setup

script: mix test

deploy:
  - provider: script
    script: config/ci/shipit.sh
    on:
      branch: master
